/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.pAML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.paml.pAML.ListRotation;
import org.xtext.example.paml.pAML.ListStyle;
import org.xtext.example.paml.pAML.Meta;
import org.xtext.example.paml.pAML.PAMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Meta</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.paml.pAML.impl.MetaImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.MetaImpl#getListStyle <em>List Style</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.MetaImpl#getListRotation <em>List Rotation</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.MetaImpl#getString <em>String</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MetaImpl extends MinimalEObjectImpl.Container implements Meta
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getListStyle() <em>List Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListStyle()
   * @generated
   * @ordered
   */
  protected static final ListStyle LIST_STYLE_EDEFAULT = ListStyle.NUMBERS;

  /**
   * The cached value of the '{@link #getListStyle() <em>List Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListStyle()
   * @generated
   * @ordered
   */
  protected ListStyle listStyle = LIST_STYLE_EDEFAULT;

  /**
   * The default value of the '{@link #getListRotation() <em>List Rotation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListRotation()
   * @generated
   * @ordered
   */
  protected static final ListRotation LIST_ROTATION_EDEFAULT = ListRotation.ALTERNATING;

  /**
   * The cached value of the '{@link #getListRotation() <em>List Rotation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListRotation()
   * @generated
   * @ordered
   */
  protected ListRotation listRotation = LIST_ROTATION_EDEFAULT;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PAMLPackage.Literals.META;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.META__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ListStyle getListStyle()
  {
    return listStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListStyle(ListStyle newListStyle)
  {
    ListStyle oldListStyle = listStyle;
    listStyle = newListStyle == null ? LIST_STYLE_EDEFAULT : newListStyle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.META__LIST_STYLE, oldListStyle, listStyle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ListRotation getListRotation()
  {
    return listRotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListRotation(ListRotation newListRotation)
  {
    ListRotation oldListRotation = listRotation;
    listRotation = newListRotation == null ? LIST_ROTATION_EDEFAULT : newListRotation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.META__LIST_ROTATION, oldListRotation, listRotation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.META__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PAMLPackage.META__NAME:
        return getName();
      case PAMLPackage.META__LIST_STYLE:
        return getListStyle();
      case PAMLPackage.META__LIST_ROTATION:
        return getListRotation();
      case PAMLPackage.META__STRING:
        return getString();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PAMLPackage.META__NAME:
        setName((String)newValue);
        return;
      case PAMLPackage.META__LIST_STYLE:
        setListStyle((ListStyle)newValue);
        return;
      case PAMLPackage.META__LIST_ROTATION:
        setListRotation((ListRotation)newValue);
        return;
      case PAMLPackage.META__STRING:
        setString((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PAMLPackage.META__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PAMLPackage.META__LIST_STYLE:
        setListStyle(LIST_STYLE_EDEFAULT);
        return;
      case PAMLPackage.META__LIST_ROTATION:
        setListRotation(LIST_ROTATION_EDEFAULT);
        return;
      case PAMLPackage.META__STRING:
        setString(STRING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PAMLPackage.META__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PAMLPackage.META__LIST_STYLE:
        return listStyle != LIST_STYLE_EDEFAULT;
      case PAMLPackage.META__LIST_ROTATION:
        return listRotation != LIST_ROTATION_EDEFAULT;
      case PAMLPackage.META__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", listStyle: ");
    result.append(listStyle);
    result.append(", listRotation: ");
    result.append(listRotation);
    result.append(", string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //MetaImpl
