/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.pAML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.paml.pAML.Meta;
import org.xtext.example.paml.pAML.PAML;
import org.xtext.example.paml.pAML.PAMLPackage;
import org.xtext.example.paml.pAML.Task;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PAML</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.paml.pAML.impl.PAMLImpl#getMetaInformation <em>Meta Information</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.PAMLImpl#getPrecode <em>Precode</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.PAMLImpl#getTasks <em>Tasks</em>}</li>
 *   <li>{@link org.xtext.example.paml.pAML.impl.PAMLImpl#getPostcode <em>Postcode</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PAMLImpl extends MinimalEObjectImpl.Container implements PAML
{
  /**
   * The cached value of the '{@link #getMetaInformation() <em>Meta Information</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetaInformation()
   * @generated
   * @ordered
   */
  protected Meta metaInformation;

  /**
   * The default value of the '{@link #getPrecode() <em>Precode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecode()
   * @generated
   * @ordered
   */
  protected static final String PRECODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrecode() <em>Precode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecode()
   * @generated
   * @ordered
   */
  protected String precode = PRECODE_EDEFAULT;

  /**
   * The cached value of the '{@link #getTasks() <em>Tasks</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTasks()
   * @generated
   * @ordered
   */
  protected Task tasks;

  /**
   * The default value of the '{@link #getPostcode() <em>Postcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostcode()
   * @generated
   * @ordered
   */
  protected static final String POSTCODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPostcode() <em>Postcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostcode()
   * @generated
   * @ordered
   */
  protected String postcode = POSTCODE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PAMLImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PAMLPackage.Literals.PAML;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Meta getMetaInformation()
  {
    return metaInformation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMetaInformation(Meta newMetaInformation, NotificationChain msgs)
  {
    Meta oldMetaInformation = metaInformation;
    metaInformation = newMetaInformation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__META_INFORMATION, oldMetaInformation, newMetaInformation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetaInformation(Meta newMetaInformation)
  {
    if (newMetaInformation != metaInformation)
    {
      NotificationChain msgs = null;
      if (metaInformation != null)
        msgs = ((InternalEObject)metaInformation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PAMLPackage.PAML__META_INFORMATION, null, msgs);
      if (newMetaInformation != null)
        msgs = ((InternalEObject)newMetaInformation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PAMLPackage.PAML__META_INFORMATION, null, msgs);
      msgs = basicSetMetaInformation(newMetaInformation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__META_INFORMATION, newMetaInformation, newMetaInformation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPrecode()
  {
    return precode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrecode(String newPrecode)
  {
    String oldPrecode = precode;
    precode = newPrecode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__PRECODE, oldPrecode, precode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Task getTasks()
  {
    return tasks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTasks(Task newTasks, NotificationChain msgs)
  {
    Task oldTasks = tasks;
    tasks = newTasks;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__TASKS, oldTasks, newTasks);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTasks(Task newTasks)
  {
    if (newTasks != tasks)
    {
      NotificationChain msgs = null;
      if (tasks != null)
        msgs = ((InternalEObject)tasks).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PAMLPackage.PAML__TASKS, null, msgs);
      if (newTasks != null)
        msgs = ((InternalEObject)newTasks).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PAMLPackage.PAML__TASKS, null, msgs);
      msgs = basicSetTasks(newTasks, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__TASKS, newTasks, newTasks));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPostcode()
  {
    return postcode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPostcode(String newPostcode)
  {
    String oldPostcode = postcode;
    postcode = newPostcode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PAMLPackage.PAML__POSTCODE, oldPostcode, postcode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PAMLPackage.PAML__META_INFORMATION:
        return basicSetMetaInformation(null, msgs);
      case PAMLPackage.PAML__TASKS:
        return basicSetTasks(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PAMLPackage.PAML__META_INFORMATION:
        return getMetaInformation();
      case PAMLPackage.PAML__PRECODE:
        return getPrecode();
      case PAMLPackage.PAML__TASKS:
        return getTasks();
      case PAMLPackage.PAML__POSTCODE:
        return getPostcode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PAMLPackage.PAML__META_INFORMATION:
        setMetaInformation((Meta)newValue);
        return;
      case PAMLPackage.PAML__PRECODE:
        setPrecode((String)newValue);
        return;
      case PAMLPackage.PAML__TASKS:
        setTasks((Task)newValue);
        return;
      case PAMLPackage.PAML__POSTCODE:
        setPostcode((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PAMLPackage.PAML__META_INFORMATION:
        setMetaInformation((Meta)null);
        return;
      case PAMLPackage.PAML__PRECODE:
        setPrecode(PRECODE_EDEFAULT);
        return;
      case PAMLPackage.PAML__TASKS:
        setTasks((Task)null);
        return;
      case PAMLPackage.PAML__POSTCODE:
        setPostcode(POSTCODE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PAMLPackage.PAML__META_INFORMATION:
        return metaInformation != null;
      case PAMLPackage.PAML__PRECODE:
        return PRECODE_EDEFAULT == null ? precode != null : !PRECODE_EDEFAULT.equals(precode);
      case PAMLPackage.PAML__TASKS:
        return tasks != null;
      case PAMLPackage.PAML__POSTCODE:
        return POSTCODE_EDEFAULT == null ? postcode != null : !POSTCODE_EDEFAULT.equals(postcode);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (precode: ");
    result.append(precode);
    result.append(", postcode: ");
    result.append(postcode);
    result.append(')');
    return result.toString();
  }

} //PAMLImpl
