/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PAMLUiModule extends AbstractPAMLUiModule {

	public PAMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
