/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PAMLRuntimeModule extends AbstractPAMLRuntimeModule {
}
