/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.paml.ui.internal.PamlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PAMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PamlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PamlActivator activator = PamlActivator.getInstance();
		return activator != null ? activator.getInjector(PamlActivator.ORG_XTEXT_EXAMPLE_PAML_PAML) : null;
	}

}
