/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.paml.PAMLRuntimeModule;
import org.xtext.example.paml.PAMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PAMLIdeSetup extends PAMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PAMLRuntimeModule(), new PAMLIdeModule()));
	}
	
}
