/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.paml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.paml.ui.internal.PamlActivator;

public class PAMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PamlActivator.getInstance().getInjector("org.xtext.example.paml.PAML");
	}

}
